; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++2a
build_unflags = -std=gnu++11
lib_deps = 
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    adafruit/Adafruit PCF8574@^1.1.1
; To use espressif/arduino-esp32 as an ESP-IDF Component:
; lib_compat_mode = off
; platform_packages = framework-arduinoespressif33 @ https://github.com/espressif/arduino-esp32.git
; board_build.embed_txtfiles =
;     managed_components/espressif__esp_insights/server_certs/https_server.crt
;     managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
;     managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
;     managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt